Algoritmo "Area de uma circunferencia"
//1.Faça um algoritmo para calcular a área de uma circunferência,
//considerando a fórmula ÁREA = p * RAIO². Utilize as variáveis AREA e RAIO,
//a constante p (pi =3,14159) e os operadores aritméticos de multiplicação.


Var
AREA, RAIO : real


Inicio
escreval ("calculo da área de uma circunferencia: ")
escreval ("diga o tamanho do raio: ")
leia (RAIO)
AREA <- (pi * RAIO^2)
escreval ("O tamanho da área da circunferencia é: ",AREA)

Fimalgoritmo