Algoritmo "COVID"
// Crie um algoritmo que mostre na tela o total da sequência:
// 1, 1/2, 1/3, 1/4, ...até... 1/20.
Var
   matriz : vetor [0..2,0..3] de inteiro

   pais : caracter
   casos, mortes : real
   linha, coluna : inteiro


inicio
   escreval ("Casos e Mortes por Covid ao redor do globo: Países mais afetados")

   para linha de 0 ate 2 faca
      para coluna de o ate 3 faca
         escreval ("Digite um número para inserir na matriz")
         leia (matriz[linha,coluna])
      fimpara
   fimpara

   escreval ("PAÍS - TOTAL DE CASOS - NOVOS CASOS")



Fimalgoritmo