Algoritmo "exercicio 13"
// 13.Criar um algoritmo que leia 10 números pelo teclado e exiba os números
// na ordem correta que os números foram digitados.
Var
 numeros : vetor [1..10] de inteiro
 i : inteiro
 



Inicio

para i de 1 ate 10 faca
escreva ("Dígite um número: ")
leia (numeros[i])
fimpara

escreva ("Números na ordem correta: ")
para i de 1 ate 10 faca
escreva (numeros[i])
fimpara




Fimalgoritmo