Algoritmo "Exercicio 1"
// Peça para o usuário entrar com um número e verifique se ele é par ou ímpar,
//informando o re- sultado na tela. Observação: para o número ser par, o resto
//de sua divisão por dois deverá ser igual a zero.
Var
numero : inteiro


Inicio
    escreval ("Diga um numero: ")
    leia (numero)
se numero % 2 = 0 entao
    escreval ("O numero", numero, "  é par! ")
senao
    escreval (" O numero", numero, "  é impar! ")
fimse

Fimalgoritmo