Algoritmo "exercício 3"
// 3. Faça um algoritmo que:
//a) Leia um número inteiro;
//b) Leia um segundo número inteiro;
//c) Efetue a adição dos dois valores;
//d) Apresente o valor calculado.


Var
n1, n2, soma : inteiro


Inicio
escreval ("Digíte um número inteiro: ")
leia (n1)
escreval ("Digíte outro número inteiro: ")
leia (n2)
soma <- n1 + n2
escreval ("A soma dos valores é: ",soma)

Fimalgoritmo